version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blocks
    restart: unless-stopped
    networks:
      - reverse-proxy-nw

networks:
  reverse-proxy-nw:
    external: true
