import { Block, GridContent, Empty } from "../types";Block.I

export const WIDTH:number = 10;

export const HEIGHT:number = 20;

export const initialGrid:GridContent = Array.from(Array(HEIGHT), () => Array(WIDTH).fill({ content: Empty.Empty, sticks: false }));

export const fakeGrid:GridContent = [
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Block.I, sticks:true}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Block.J, sticks:true}, {content:Block.I, sticks:true}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Empty.Empty, sticks:false}, {content:Block.J, sticks:true}, {content:Block.I, sticks:true}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}],
    [{content:Block.J, sticks:true}, {content:Block.J, sticks:true}, {content:Block.I, sticks:true}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}, {content:Empty.Empty, sticks:false}]
]